(import (micro dagopoly)
    (micro fs)
	(micro stream)
	(micro dagopoly-python))
(define block-python (block-ipc "python"))
(define block-test-ipc (block-python "../dagopoly-py/test/autobin/test-ipc-receive.py"))
(define b1 (block-test-ipc "expr3"))
(display (format "sig=~s\n" (block-sig b1)))
(display (format "get=~s\n" (s->list (block-get b1))))
